# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft'), ('RE', 'Removed')], default='DR', max_length=2),
        ),
    ]
