# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_article_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='patch_reverse',
            field=models.TextField(default=datetime.datetime(2015, 12, 12, 19, 46, 57, 53899, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
