# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
