# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_contents_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
